<?php
define('TRANSLATIONS', [
  'nav_dashboard'=>['ar'=>'لوحة التحكم','en'=>'Dashboard'],
  'nav_new_report'=>['ar'=>'تقرير جديد','en'=>'New Report'],
  'nav_search'=>['ar'=>'بحث متقدم','en'=>'Advanced Search'],
  'nav_history'=>['ar'=>'سجل المركبات','en'=>'Vehicle History'],
  'nav_statistics'=>['ar'=>'الإحصائيات','en'=>'Statistics'],
  'nav_users'=>['ar'=>'إدارة المستخدمين','en'=>'User Management'],
  'nav_settings'=>['ar'=>'الإعدادات','en'=>'Settings'],
  'nav_logout'=>['ar'=>'تسجيل الخروج','en'=>'Logout'],
  'login_title'=>['ar'=>'تسجيل الدخول','en'=>'Login'],
  'login_username'=>['ar'=>'اسم المستخدم','en'=>'Username'],
  'login_password'=>['ar'=>'كلمة المرور','en'=>'Password'],
  'login_btn'=>['ar'=>'دخول','en'=>'Sign In'],
  'login_error'=>['ar'=>'اسم المستخدم أو كلمة المرور غير صحيحة','en'=>'Incorrect username or password'],
  'role_admin'=>['ar'=>'مدير النظام','en'=>'Administrator'],
  'role_manager'=>['ar'=>'مدير الورشة','en'=>'Workshop Manager'],
  'role_technician'=>['ar'=>'فني','en'=>'Technician'],
  'role_viewer'=>['ar'=>'مشاهد فقط','en'=>'Viewer'],
  'total_reports'=>['ar'=>'إجمالي التقارير','en'=>'Total Reports'],
  'today_reports'=>['ar'=>'تقارير اليوم','en'=>"Today's Reports"],
  'complete_reports'=>['ar'=>'تقارير مكتملة','en'=>'Complete Reports'],
  'this_month'=>['ar'=>'هذا الشهر','en'=>'This Month'],
  'report_number'=>['ar'=>'رقم التقرير','en'=>'Report No.'],
  'plate_number'=>['ar'=>'رقم اللوحة','en'=>'Plate Number'],
  'chassis_number'=>['ar'=>'رقم الشاسيه','en'=>'Chassis Number'],
  'brand'=>['ar'=>'الماركة','en'=>'Brand'],
  'model'=>['ar'=>'الموديل','en'=>'Model'],
  'year'=>['ar'=>'سنة الصنع','en'=>'Year'],
  'fuel_type'=>['ar'=>'نوع الوقود','en'=>'Fuel Type'],
  'mileage'=>['ar'=>'الكيلومتر','en'=>'Mileage'],
  'package'=>['ar'=>'نوع الباقة','en'=>'Package Type'],
  'date_inspection'=>['ar'=>'تاريخ الفحص','en'=>'Inspection Date'],
  'time_in'=>['ar'=>'ساعة الدخول','en'=>'Time In'],
  'time_out'=>['ar'=>'ساعة الخروج','en'=>'Time Out'],
  'license_seen'=>['ar'=>'هل رأيت الرخصة؟','en'=>'License Seen?'],
  'technician'=>['ar'=>'الفني','en'=>'Technician'],
  'customer_name'=>['ar'=>'اسم المشتري','en'=>'Customer Name'],
  'customer_phone'=>['ar'=>'هاتف المشتري','en'=>'Customer Phone'],
  'seller_name'=>['ar'=>'اسم البائع','en'=>'Seller Name'],
  'seller_phone'=>['ar'=>'هاتف البائع','en'=>'Seller Phone'],
  'status_draft'=>['ar'=>'مسودة','en'=>'Draft'],
  'status_complete'=>['ar'=>'مكتمل','en'=>'Complete'],
  'btn_save'=>['ar'=>'حفظ','en'=>'Save'],
  'btn_save_draft'=>['ar'=>'حفظ مسودة','en'=>'Save Draft'],
  'btn_save_finish'=>['ar'=>'حفظ وإنهاء','en'=>'Save & Finish'],
  'btn_edit'=>['ar'=>'تعديل','en'=>'Edit'],
  'btn_delete'=>['ar'=>'حذف','en'=>'Delete'],
  'btn_view'=>['ar'=>'عرض','en'=>'View'],
  'btn_print'=>['ar'=>'طباعة PDF','en'=>'Print PDF'],
  'btn_search'=>['ar'=>'بحث','en'=>'Search'],
  'btn_clear'=>['ar'=>'مسح','en'=>'Clear'],
  'btn_cancel'=>['ar'=>'إلغاء','en'=>'Cancel'],
  'btn_send'=>['ar'=>'إرسال','en'=>'Send'],
  'btn_new_user'=>['ar'=>'مستخدم جديد','en'=>'New User'],
  'btn_new_report'=>['ar'=>'تقرير جديد','en'=>'New Report'],
  'btn_export_csv'=>['ar'=>'تصدير CSV','en'=>'Export CSV'],
  'search_title'=>['ar'=>'بحث متقدم','en'=>'Advanced Search'],
  'search_date_from'=>['ar'=>'من تاريخ','en'=>'Date From'],
  'search_date_to'=>['ar'=>'إلى تاريخ','en'=>'Date To'],
  'search_status'=>['ar'=>'الحالة','en'=>'Status'],
  'search_fuel'=>['ar'=>'نوع الوقود','en'=>'Fuel Type'],
  'search_tech'=>['ar'=>'الفني','en'=>'Technician'],
  'search_results'=>['ar'=>'نتائج البحث','en'=>'Search Results'],
  'no_results'=>['ar'=>'لا توجد نتائج','en'=>'No results found'],
  'history_title'=>['ar'=>'سجل المركبة','en'=>'Vehicle History'],
  'history_search'=>['ar'=>'ابحث بالشاسيه أو اللوحة','en'=>'Search by chassis or plate'],
  'history_count'=>['ar'=>'عدد الفحوصات','en'=>'Inspection Count'],
  'first_inspection'=>['ar'=>'أول فحص','en'=>'First Inspection'],
  'last_inspection'=>['ar'=>'آخر فحص','en'=>'Last Inspection'],
  'stats_title'=>['ar'=>'الإحصائيات','en'=>'Statistics'],
  'stats_monthly'=>['ar'=>'التقارير الشهرية','en'=>'Monthly Reports'],
  'stats_brands'=>['ar'=>'أكثر الماركات فحصاً','en'=>'Most Inspected Brands'],
  'users_title'=>['ar'=>'إدارة المستخدمين','en'=>'User Management'],
  'user_username'=>['ar'=>'اسم المستخدم','en'=>'Username'],
  'user_fullname_ar'=>['ar'=>'الاسم الكامل (عربي)','en'=>'Full Name (Arabic)'],
  'user_fullname_en'=>['ar'=>'الاسم الكامل (إنجليزي)','en'=>'Full Name (English)'],
  'user_email'=>['ar'=>'البريد الإلكتروني','en'=>'Email'],
  'user_phone'=>['ar'=>'رقم الهاتف','en'=>'Phone'],
  'user_role'=>['ar'=>'الصلاحية','en'=>'Role'],
  'user_status'=>['ar'=>'الحالة','en'=>'Status'],
  'user_active'=>['ar'=>'نشط','en'=>'Active'],
  'user_inactive'=>['ar'=>'معطل','en'=>'Inactive'],
  'user_password'=>['ar'=>'كلمة المرور','en'=>'Password'],
  'user_created'=>['ar'=>'تم إنشاء الحساب بنجاح','en'=>'User created successfully'],
  'user_updated'=>['ar'=>'تم تحديث الحساب','en'=>'User updated successfully'],
  'user_deleted'=>['ar'=>'تم حذف الحساب','en'=>'User deleted'],
  'user_lang'=>['ar'=>'اللغة المفضلة','en'=>'Preferred Language'],
  'notif_title'=>['ar'=>'إرسال إشعار','en'=>'Send Notification'],
  'notif_sent'=>['ar'=>'تم الإرسال بنجاح','en'=>'Sent successfully'],
  'notif_failed'=>['ar'=>'فشل الإرسال','en'=>'Send failed'],
  'img_upload'=>['ar'=>'رفع صورة','en'=>'Upload Image'],
  'img_caption'=>['ar'=>'وصف الصورة','en'=>'Caption'],
  'audit_title'=>['ar'=>'سجل العمليات','en'=>'Audit Log'],
  'audit_user'=>['ar'=>'المستخدم','en'=>'User'],
  'audit_action'=>['ar'=>'العملية','en'=>'Action'],
  'audit_ip'=>['ar'=>'عنوان IP','en'=>'IP Address'],
  'audit_time'=>['ar'=>'الوقت','en'=>'Time'],
  'yes'=>['ar'=>'نعم','en'=>'Yes'],
  'no'=>['ar'=>'لا','en'=>'No'],
  'all'=>['ar'=>'الكل','en'=>'All'],
  'notes'=>['ar'=>'ملاحظات','en'=>'Notes'],
  'actions'=>['ar'=>'إجراءات','en'=>'Actions'],
  'error'=>['ar'=>'خطأ','en'=>'Error'],
  'success'=>['ar'=>'تم بنجاح','en'=>'Success'],
  'confirm_delete'=>['ar'=>'هل أنت متأكد من الحذف؟','en'=>'Are you sure you want to delete?'],
  'no_data'=>['ar'=>'لا توجد بيانات','en'=>'No data available'],
  'saved'=>['ar'=>'تم الحفظ بنجاح ✅','en'=>'Saved successfully ✅'],
  'records'=>['ar'=>'سجل','en'=>'records'],
  'required_field'=>['ar'=>'هذا الحقل مطلوب','en'=>'This field is required'],
]);

function currentLang(): string {
    if (session_status()===PHP_SESSION_NONE) session_start();
    return $_SESSION['lang'] ?? 'ar';
}
function t(string $key, string $lang=''): string {
    $lang = $lang ?: currentLang();
    $tr   = TRANSLATIONS;
    if (!isset($tr[$key])) return $key;
    return $tr[$key][$lang] ?? $tr[$key]['ar'] ?? $key;
}
function setLang(string $lang): void {
    if (session_status()===PHP_SESSION_NONE) session_start();
    if (in_array($lang,['ar','en'])) $_SESSION['lang']=$lang;
}
function langDir(): string { return currentLang()==='ar'?'rtl':'ltr'; }
function langAttr(): string { return currentLang(); }
